Initialize the samples key and skip counter when samples is empty
spreaker/prometheus_client_php pull request #1
Opened 2020-10-19 16:43 UTC by dymissy

This patch should fix the errors we experienced on Kibana due to non-existing APC values keys.

https://kibana.spreaker.com/app/kibana#/discover?_g=(refreshInterval:('$$hashKey':'object:3441',display:'45%20seconds',pause:!f,section:1,value:45000),time:(from:now-4d,mode:relative,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'logstash-*',key:message,negate:!f,type:phrase,value:'PHP%20message:%20PHP%20Fatal%20error:%20Uncaught%20TypeError:%20Argument%201%20passed%20to%20Prometheus%5CStorage%5CAPC::sortSamples()%20must%20be%20of%20the%20type%20array'),query:(match:(message:(query:'PHP%20message:%20PHP%20Fatal%20error:%20Uncaught%20TypeError:%20Argument%201%20passed%20to%20Prometheus%5CStorage%5CAPC::sortSamples()%20must%20be%20of%20the%20type%20array',type:phrase))))),index:'logstash-*',interval:auto,query:(match_all:()),sort:!('@timestamp',asc))

2020-10-19 16:54 UTC, roccozanni requested changes

2020-10-19 16:54 UTC, roccozanni commented on src/Prometheus/Storage/APC.php
> +                'sample' => [],
Missing an `s` here

2020-10-19 17:15 UTC, dymissy commented on src/Prometheus/Storage/APC.php
> +                'sample' => [],
Fixed, thanks

2020-10-19 17:17 UTC, hugo-spreaker approved these changes
🙏  We had 4 eyes on it and a typo slipped 😅

2020-10-20 07:21 UTC, roccozanni approved these changes
Changes are good now, but please update the PR description to explain what this fix is about, including the error message we were getting

2020-10-20 07:48 UTC, merged